name: Update README Collection

on:
  push:
    branches:
      - master
    paths:
      - "*"       # trigger on root-level changes
      - "*/**"    # trigger on changes inside root-level folders

permissions:
  contents: write   # 👈 allow GitHub Actions to push changes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Update README
        run: |
          python .github/scripts/update_collection.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🔄 Auto-update collection in README" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
